export const ChemistryFriendlyUnits = {
    "EQV_EQUIV": "equiv",
    "VOL_FT3": "ft",
    "GRAM": "g",
    "MASS_G": "g",
    "GG": "g/g",
    "MASSRT_G_G_LM": "g/g LR",
    "MASSRT_G_G_LM_PURE": "g/g LR PURE",
    "GMOL": "g/mol",
    "MASSRT_G_MOL_LM": "g/mol LR",
    "VOL_GAL_BRIT": "gal (UK)",
    "VOL_GAL": "gal (US)",
    "KILOGRAM": "kg",
    "MASS_KG": "kg",
    "MASSRT_KG_100G_LM": "kg/100g LR",
    "MASSRT_KG_G_LM": "kg/g LR",
    "KGPERKG": "kg/kg",
    "MASSRT_KG_KG_LM": "kg/kg LR",
    "KGPMOLE": "kg/mol",
    "MASSRT_KG_MOL_LM": "kg/mol LR",
    "LITER": "L",
    "VOL_L": "L",
    "LPERHUNDREDG": "L/100g",
    "VOLRT_L_100G_LM": "L/100g LR",
    "LPERG": "L/g",
    "VOLRT_L_G_LM": "L/g LR",
    "LPERKG": "L/kg",
    "VOLRT_L_KG_LM": "L/kg LR",
    "VOLRT_L_KG_LM_PURE": "L/kg LR PURE",
    "LMOL": "L/mol",
    "VOLRT_L_MOL_LM": "L/mol LR",
    "MASS_LBS": "lbs",
    "MOLAR": "M",
    "MOLRT_EQUIV_M": "M",
    "MASS_MG": "mg",
    "MILLIGRAM": "mg",
    "MILLILITER": "mL",
    "VOL_ML": "mL",
    "MLPERG": "mL/g",
    "VOLRT_ML_G_LM": "mL/g LR",
    "VOLRT_ML_G_LM_PURE": "mL/g LR PURE",
    "MLMMOL": "ml/mmol",
    "VOLRT_ML_MMOL_LM": "mL/mmol LR",
    "MILLIMOLE": "mmol",
    "MOL_MMOLES": "mmol",
    "MOLRT_MMOLES_G_LM_PURE": "mmol/g LR PURE",
    "MOL_MOLES": "mol",
    "MOLE": "mol",
    "MOLRT_MOLES_100G_LM": "mol/100g LR",
    "MOLRT_MOLES_G_LM": "mol/g LR",
    "MOLRT_MOLES_KG_LM": "mol/kg LR",
    "VOLRT_MOL_LM_L": "mol/L",
    "MOLMOL": "equiv",
    "MOLRT_MOLES_MOL_LM": "mol/mol LR",
    "NANOMOLE": "nmol",
    "UNDEFINED": "undefined",
    "MICROGRAM": "μg",
    "MICROLITER": "μL",
    "VOL_UL": "μL",
    "MICROMOLE": "μmol",
    "MOL_UMOLES": "μmol",
    "CONC_M": "M",
    "CONC_WT_WT": "mass fraction",
    "CONC_ML_100ML": "mL/100mL",
    "MOLEPERCENT": "mol%",
    "VOLPERCENT": "vol%",
    "UMOLELITER": "μmol/L",
    "MOLELITER": "mol/L",
    "CONC_G_ML": "g/mL",
    "CONC_MM": "CONC_MM",
    "MMOLEMLITER": "mmol/mL",
    "GRAMPERHUNDREDGRAM": "g/100g",
    "MGMG": "mg/mg",
    "PURITY_MMOL_G": "mmol/g",
    "LOADING_MOL_100G": "mol/100g",
    "MOLG": "mol/g",
    "MILLIGRAMG": "mg/g",
    "PURITY_WT_WT": "mass fraction",
    "CONC_G_L": "g/L",
    "PURITY_UMOL_G": "μmol/g",
    "MOLFRACTION": "mol fraction",
    "GRAMPERKG": "g/kg",
    "CONC_WT_VOL": "wt%",
    "COMP_WT_WT": "mass fraction",
    "PURITY_MOL_100G": "mol/100g",
    "CONC_MOL_100G": "mol/100g",
    "UMOLEULITER": "μmol/μL",
    "CONC_UM": "μM",
    "PURITY_G_100G": "g/100g",
    "CONC_VOL_VOL": "CONC_VOL_VOL",
    "MGPERML": "mg/mL",
    "MMOLG": "mmol/g",
    "MMOLELITER": "mmol/L",
    "MASSPERCENT": "mass%",
    "LOADING_MMOL_G": "mmol/g",
    "CONC_MG_ML": "mg/mL",
    "CONC_G_100ML": "g/100mL",
    "CONC_G_100G": "g/100g",
    "MOLML": "mol/mL",
    "MOLKG": "mol/kg",
    "NMOLELITER": "nmol/L"
};
